require('dotenv').config()

const PORT = process.env.PORT
const DATABASE_USER = process.env.DATABASE_USER
const DATABASE_PASSWORD = process.env.DATABASE_PASSWORD
const DATABASE_NAME = process.env.DATABASE_NAME
const DATABASE_HOST = process.env.DATABASE_HOST
const USER_IMAGE_PATH = process.env.USER_IMAGE_PATH
const ROOM_IMAGE_PATH = process.env.ROOM_IMAGE_PATH 
const DEVICE_IMAGE_PATH = process.env.DEVICE_IMAGE_PATH 
const JWT_SECRET = process.env.JWT_SECRET
const HOST = process.env.HOST

module.exports = {
    PORT: PORT,
    DATABASE_USER: DATABASE_USER,
    DATABASE_PASSWORD: DATABASE_PASSWORD,
    DATABASE_NAME: DATABASE_NAME,
    DATABASE_HOST: DATABASE_HOST,
    USER_IMAGE_PATH: USER_IMAGE_PATH,
    ROOM_IMAGE_PATH: ROOM_IMAGE_PATH,
    DEVICE_IMAGE_PATH: DEVICE_IMAGE_PATH,
    JWT_SECRET: JWT_SECRET,
    HOST: HOST
}
